### ISSUE TITLE
Bundeswehr Woodland Faction

### ISSUE THREAD

**Issue by Real-ADK** [PXG-Arma/Scripts#42]
Missing items / location:
MAT Gunner - Tourniquet / uniform

MORT Lead - pistol mag / backpack
MORT Gun - pistol mag / backpack

AA Gun - Tourniquet / uniform

Armour Commander - pistol / backpack
Armour Gunner - pistol / backpack

**Comment by Leubzo** [comment]
- MAT Gunner receives tourniquet with old code.
- AA Gun receives tourniquet with old code.
- Removed pistol and pistol ammo from faction.
