### ISSUE TITLE
German Special Forces Faction

### ISSUE THREAD

**Issue by Real-ADK** [PXG-Arma/Scripts#43]
Missing items / location:
MAT Gunner - tourniquet / uniform
AA Gunner - tourniquet / uniform

**Comment by DrJaffas22** [comment]
LAT borked

**Comment by Leubzo** [comment]
- Tourniquet gets added with old code.
- Fixed LAT by adding the correct "BWA3_RGW90_Loaded" item ID instead of "BWA3_RGW90" that comes without a round loaded.
