### ISSUE TITLE
Norwegian Army Winter Modern Faction

### ISSUE THREAD

**Issue by Real-ADK** [PXG-Arma/Scripts#44]
Missing item / location:
HAT Lead -FGM 148 mag / backpack

MORT Lead - pistol mag / backpack 
MORT Gun - pistol mag / backpack

Armour Commander - pistol mag / backpack
Armour Crew - pistol mag / backpack

**Comment by Leubzo** [comment]
- Removed FGM 148 mag from loadouts because it's too heavy, HAT team should get reloads from resupply crates instead.
- Removed pistols and pistol mags from faction.
