### ISSUE TITLE
Norwegian Army Woodland Modern Faction

### ISSUE THREAD

**Issue by Real-ADK** [PXG-Arma/Scripts#45]
Missing item / location:
HAT Lead -FGM 148 mag / backpack

MORT Lead - pistol mag / backpack
MORT Gun - pistol mag / backpack

Armour Commander - pistol mag / backpack
Armour Crew - pistol mag / backpack

**Comment by Leubzo** [comment]
- Reference https://github.com/PXG-Arma/Scripts/issues/44#issuecomment-1817154427
