### ISSUE TITLE
US ARMY Mechanized Modern Faction

### ISSUE THREAD

**Issue by Real-ADK** [PXG-Arma/Scripts#46]
Missing item / location:
AR - Cable tie / vest

HAT Lead - FGM 148 mag / backpack 
HAT Gun - FGM 148 mag / backpack

AA Lead - entrenching tool / backpack
AA Gun - entrenching tool / backpack

**Comment by Leubzo** [comment]
- Moved grenades for AR to backpack
- Removed FGM 148 mag from loadouts because it's too heavy, HAT team should get reloads from resupply crates instead.
- Upgraded AA roles to the VSM Carryall backpack.
