### ISSUE TITLE
US ARMY Early Faction

### ISSUE THREAD

**Issue by Real-ADK** [PXG-Arma/Scripts#47]
Missing items / location:
HMG Lead - 20rnd 3cb rifle mag 556 / backpack
HMG Gunner - 20rnd 3cb rifle mag 556 / backpack

Mortar Lead - 20rnd 3cb rifle mag 556 / backpack
Mortar Gun - 20rnd 3cb rifle mag 556 / backpack

**Comment by Leubzo** [comment]
- Removed mags from backpacks.
