### ISSUE TITLE
US Marine Corps Marpat Faction

### ISSUE THREAD

**Issue by Real-ADK** [PXG-Arma/Scripts#50]
Missing item / location:

MAT Gunner - Tourniquet / Uniform

MORT Lead - Entrenching tool / vest 
MORT Gun - Pistol mag / backpack

Recon Specialist - hang grenade / vest

Armour commander - entrenching tool / vest
Armour crew - entrenching tool / vest

**Comment by Leubzo** [comment]
- Tourniquet gets added fine in current code.
- MORT Lead has no space left, entrenching tool not required anyway.
- Removed pistol and pistol mags from faction.
- Specialist moved grenades to backpack to make space in vest.
- Changed armour crew vest to default for more space for entrenching tools.
