### ISSUE TITLE
US Special Forces Raiders Modern Faction

### ISSUE THREAD

**Issue by Real-ADK** [PXG-Arma/Scripts#51]
Missing item / location:

MAT Gunner - Tourniquet / uniforms 

MORT Lead - 20rnd scar mag / backpack
MORT Gunner - 20rnd scar mag / backpack

**Comment by Leubzo** [comment]
- MAT Gunner: Tourniquet is added fine in current code.
- MORT Lead/Gunner: Does not cause issues, just doesn't add mags since backpack cannot hold items.
