### ISSUE TITLE
US Delta Late Faction

### ISSUE THREAD

**Issue by Real-ADK** [PXG-Arma/Scripts#52]
Missing item / location:

Shitty Heavy grenadier - cable tie / vest
AR - cable tie / vest

MORT Lead - ACE DAGR / backpack 
MORT Gun - 30rnd 556 red tracer mag / backpack

Recon Marksman - Hand grenade / Vest

**Comment by Leubzo** [comment]
- Moved pistol mags to backpack for Heavy Grenadier.
- Moved grenades to backpack for AR.
- Moved DAGR to vest for Mortar Lead.
- Moved grenades to backpack for Recon Marksman.
