### ISSUE TITLE
AR Resupply Irish faction 

### ISSUE THREAD

**Issue by DrJaffas22** [PXG-Arma/Scripts#55]
No AR Resup for irish faction

**Comment by DrJaffas22** [comment]
https://github.com/DrJaffas22/Scripts

**Comment by DrJaffas22** [comment]
update to this MMG also have wrong resup will add to fork

**Comment by Leubzo** [comment]
- Added AR resupply.
- Changed MMG resupply to 3CB belts to avoid potential issues with the weapon.
