### ISSUE TITLE
List of factions without implementation

### ISSUE THREAD

**Issue by chloris-pale-green** [PXG-Arma/Scripts#82]
These factions variants are listed in faction variant lists, but lack actual implementation, so they trigger errors. Should be removed or commented out until implemented:
- Sayeret(WD) Modern (Israeli)
- Islamic Revolutionary Guard Late
- Jegertroppen Modern (Norwegians)

**Comment by DrJaffas22** [comment]
Latest Pull comments out norway all others correct as is in latest scripts
