### ISSUE TITLE
Colombian Armed Forces lacks platoon medic loadout

### ISSUE THREAD

**Issue by chloris-pale-green** [PXG-Arma/Scripts#84]
![Screenshot_20240825_193836](https://github.com/user-attachments/assets/47f43fcf-adb9-40e7-963c-ad6e38626402)

**Comment by Lortmil** [comment]
Added the platoon medic to loadoutlist

**Comment by chloris-pale-green** [comment]
There are additional things to check about the faction:

- Automatic rifleman comes with the wrong ammo.
- PLT lead and SQ lead have 40 mm grenades, but no launchers.
- AR resupply has wrong ammo.

**Comment by DrJaffas22** [comment]
All correct as is in latest scripts
